base_models:
  gemma2-2b:
    name: "google/gemma-2-2b-it"
    display_name: "Gemma 2 2B Instruct"
    size_gb: 4
    context_length: 8192
    language: "multilingual"
    recommended_batch_size: 2
    description: "軽量版Gemma2モデル（命令調整済み）"
    
  elyza-8b:
    name: "elyza/Llama-3-ELYZA-JP-8B"
    display_name: "ELYZA Japanese 8B"
    size_gb: 16
    context_length: 8192
    language: "ja"
    recommended_batch_size: 1
    description: "日本語に特化したLlama-3ベースのモデル"

task_types:
  qa:
    name: "質問応答"
    description: "質問に対する回答を生成するタスク"
    prompt_template: |
      ### 質問:
      {question}
      
      ### 回答:
      {answer}
      
  chat:
    name: "チャット"
    description: "対話型のチャットタスク"
    prompt_template: |
      ### ユーザー:
      {user}
      
      ### アシスタント:
      {assistant}
      
  instruction:
    name: "指示実行"
    description: "指示に従って回答を生成するタスク"
    prompt_template: |
      ### 指示:
      {instruction}
      
      ### 回答:
      {output}
      
  summary:
    name: "要約"
    description: "テキストの要約を生成するタスク"
    prompt_template: |
      ### 元テキスト:
      {text}
      
      ### 要約:
      {summary}

dataset_templates:
  alpaca_ja:
    name: "Alpaca Japanese"
    columns:
      instruction: "instruction"
      input: "input"
      output: "output"
    format: "instruction"
    
  oasst_ja:
    name: "OpenAssistant Japanese"
    columns:
      user: "user"
      assistant: "assistant"
    format: "chat"
    
  custom_qa:
    name: "カスタム質問応答"
    columns:
      question: "question"
      answer: "answer"
    format: "qa"